/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day1

import java.nio.file.Files
import kotlin.io.path.Path

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    val numPairs = Files.lines(Path("input.txt"))
        .toList()
        .flatMap { str -> str.split("   ").zipWithNext() }
    println(numPairs)
}